using System.Collections.ObjectModel;
using System.Text;
using System.Text.RegularExpressions;
using StarLibEditor.Models;

namespace StarLibEditor.Services;

public class CodeGeneratorService
{
    private readonly HashSet<string> _usedVarNames = new();

    public string Generate(StarLibProject project, bool minify = false)
    {
        _usedVarNames.Clear();
        var sb = new StringBuilder();
        var useUpgraded = project.Settings.UseUpgradedStarLib;
        var starLibFile = useUpgraded ? "StarLibUpgraded.lua" : "StarLib.lua";
        var needsUpgrade = ProjectUsesUpgradedFeatures(project);

        if (!minify)
        {
            sb.AppendLine($"-- Generated by StarLib Editor v{project.Meta.AppVersion}");
            sb.AppendLine($"-- Project: {project.Meta.ProjectName}");
            sb.AppendLine($"-- Exported: {DateTime.UtcNow:o}");
            sb.AppendLine();

            if (needsUpgrade && !useUpgraded)
                sb.AppendLine("-- NOTE: This script requires StarLibUpgraded.lua, not StarLib.lua");
        }

        sb.AppendLine($"local StarLib = loadstring(readfile(\"{project.Settings.StarLibPath.Replace("\\", "/")}\"))()");
        sb.AppendLine();

        GenerateWindowConfig(sb, project, minify);
        sb.AppendLine();

        foreach (var tab in project.Tabs)
        {
            GenerateTab(sb, project, tab, minify);
            sb.AppendLine();
        }

        var result = sb.ToString();
        if (minify)
            result = Minify(result);

        return result;
    }

    private void GenerateWindowConfig(StringBuilder sb, StarLibProject project, bool minify)
    {
        var w = project.Window;
        var indent = minify ? "" : "    ";
        var nl = minify ? " " : "\n";

        if (!minify) sb.AppendLine("-- Window");
        sb.Append("local Window = StarLib:CreateWindow({");

        sb.Append($"{nl}{indent}Name = \"{EscapeLua(w.Name)}\"");

        if (w.GuiName != "StarLibGui")
            sb.Append($",{nl}{indent}GuiName = \"{EscapeLua(w.GuiName)}\"");

        if (!string.IsNullOrEmpty(w.ToggleKey))
            sb.Append($",{nl}{indent}ToggleKey = Enum.KeyCode.{w.ToggleKey}");

        var themeOverrides = w.Theme.GetOverrides();
        if (themeOverrides.Count > 0)
        {
            sb.Append($",{nl}{indent}Theme = {{");
            var first = true;
            foreach (var kv in themeOverrides.OrderBy(k => k.Key))
            {
                if (!first) sb.Append(",");
                first = false;
                var hexToRgb = ThemeModel.HexToColor(kv.Value);
                sb.Append($"{nl}{indent}{indent}{kv.Key} = Color3.fromRGB({hexToRgb.R}, {hexToRgb.G}, {hexToRgb.B})");
            }
            sb.Append($"{nl}{indent}}}");
        }

        sb.AppendLine($"{nl}}})");
    }

    private void GenerateTab(StringBuilder sb, StarLibProject project, TabModel tab, bool minify)
    {
        var tabVar = MakeSafeVarName("Tab", tab.Name);
        var indent = minify ? "" : "    ";
        var nl = minify ? " " : "\n";

        if (!minify) sb.AppendLine($"-- Tab: {tab.Name}");
        sb.AppendLine($"local {tabVar} = Window:CreateTab(\"{EscapeLua(tab.Name)}\")");

        foreach (var node in tab.Nodes)
        {
            if (!node.Enabled) continue;
            GenerateNode(sb, tabVar, node, minify);
        }
    }

    private void GenerateNode(StringBuilder sb, string tabVar, UINode node, bool minify)
    {
        var indent = minify ? "" : "    ";
        var nl = minify ? " " : "\n";

        switch (node.Type)
        {
            case WidgetType.Section:
                sb.AppendLine($"{tabVar}:CreateSection(\"{EscapeLua(GetProp(node, "Text", "Section"))}\")");
                break;

            case WidgetType.Label:
                EmitWithOptionalBinding(sb, tabVar, node, minify,
                    $"{tabVar}:CreateLabel(\"{EscapeLua(GetProp(node, "Text", "Label"))}\")");
                break;

            case WidgetType.Paragraph:
                sb.AppendLine($"{tabVar}:CreateParagraph({{");
                sb.AppendLine($"{indent}Title = \"{EscapeLua(GetProp(node, "Title", ""))}\",");
                sb.AppendLine($"{indent}Content = \"{EscapeLua(GetProp(node, "Content", ""))}\"");
                sb.AppendLine("})");
                break;

            case WidgetType.Button:
                EmitWithOptionalBinding(sb, tabVar, node, minify, null);
                sb.AppendLine($"{tabVar}:CreateButton({{");
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Button"))}\",");
                sb.AppendLine($"{indent}Callback = function()");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
                sb.Append("})");
                if (node.BindVariable != null) sb.AppendLine(); else sb.AppendLine();
                break;

            case WidgetType.Toggle:
                EmitWidgetWithConfig(sb, tabVar, node, "CreateToggle", minify, new[]
                {
                    ("Name", GetProp(node, "Name", "Toggle"), "string"),
                    ("CurrentValue", GetBoolProp(node, "CurrentValue") ? "true" : "false", "literal"),
                    ("Callback", "CALLBACK_BOOL", "callback"),
                });
                break;

            case WidgetType.Slider:
                var min = GetNumProp(node, "Min", 0);
                var max = GetNumProp(node, "Max", 100);
                var cur = GetNumProp(node, "CurrentValue", 50);
                var inc = GetNumProp(node, "Increment", 1);
                var suffix = GetProp(node, "Suffix", "");

                EmitWidgetStart(sb, tabVar, node, "CreateSlider", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Slider"))}\",");
                sb.AppendLine($"{indent}Range = {{{FormatNum(min)}, {FormatNum(max)}}},");
                sb.AppendLine($"{indent}CurrentValue = {FormatNum(cur)},");
                sb.AppendLine($"{indent}Increment = {FormatNum(inc)},");
                if (!string.IsNullOrEmpty(suffix))
                    sb.AppendLine($"{indent}Suffix = \"{EscapeLua(suffix)}\",");
                sb.AppendLine($"{indent}Callback = function(value)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
                sb.AppendLine("})");
                break;

            case WidgetType.Dropdown:
                var options = node.Props["Options"];
                var optList = options is ObservableCollection<string> oc ? oc.ToList() : new List<string>();
                var defaultVal = GetProp(node, "Default", optList.FirstOrDefault() ?? "");

                EmitWidgetStart(sb, tabVar, node, "CreateDropdown", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Dropdown"))}\",");
                sb.Append($"{indent}Options = {{");
                sb.Append(string.Join(", ", optList.Select(o => $"\"{EscapeLua(o)}\"")));
                sb.AppendLine("},");
                sb.AppendLine($"{indent}Default = \"{EscapeLua(defaultVal)}\",");
                sb.AppendLine($"{indent}Callback = function(value)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
                sb.AppendLine("})");
                break;

            case WidgetType.Input:
                EmitWidgetStart(sb, tabVar, node, "CreateInput", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Input"))}\",");
                var ph = GetProp(node, "PlaceholderText", "...");
                if (ph != "...") sb.AppendLine($"{indent}PlaceholderText = \"{EscapeLua(ph)}\",");
                var def = GetProp(node, "Default", "");
                if (!string.IsNullOrEmpty(def)) sb.AppendLine($"{indent}Default = \"{EscapeLua(def)}\",");
                if (GetBoolProp(node, "ClearOnEnter")) sb.AppendLine($"{indent}ClearOnEnter = true,");
                sb.AppendLine($"{indent}Callback = function(text)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
                sb.AppendLine("})");
                break;

            case WidgetType.Keybind:
                var keyDefault = GetProp(node, "Default", "F");
                EmitWidgetStart(sb, tabVar, node, "CreateKeybind", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Keybind"))}\",");
                sb.AppendLine($"{indent}Default = Enum.KeyCode.{keyDefault},");
                sb.AppendLine($"{indent}Callback = function(key)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end,");
                sb.AppendLine($"{indent}OnPress = function()");
                sb.AppendLine($"{indent}{indent}--[[ TODO: Add OnPress handler ]]");
                sb.AppendLine($"{indent}end");
                sb.AppendLine("})");
                break;

            case WidgetType.ColorPicker:
                var colorDef = GetProp(node, "Default", "#FFFFFF");
                var cc = ThemeModel.HexToColor(colorDef);
                EmitWidgetStart(sb, tabVar, node, "CreateColorPicker", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Color"))}\",");
                sb.AppendLine($"{indent}Default = Color3.fromRGB({cc.R}, {cc.G}, {cc.B}),");
                sb.AppendLine($"{indent}Callback = function(color)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
                sb.AppendLine("})");
                break;

            // Upgraded widgets
            case WidgetType.Separator:
                sb.AppendLine($"{tabVar}:CreateSeparator()");
                break;

            case WidgetType.Spacer:
                var spacerH = GetNumProp(node, "Height", 10);
                sb.AppendLine($"{tabVar}:CreateSpacer({{ Height = {FormatNum(spacerH)} }})");
                break;

            case WidgetType.ProgressBar:
                EmitWidgetStart(sb, tabVar, node, "CreateProgressBar", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Progress"))}\",");
                sb.AppendLine($"{indent}Min = {FormatNum(GetNumProp(node, "Min", 0))},");
                sb.AppendLine($"{indent}Max = {FormatNum(GetNumProp(node, "Max", 100))},");
                sb.AppendLine($"{indent}Default = {FormatNum(GetNumProp(node, "Default", 0))},");
                if (GetBoolProp(node, "ShowLabel")) sb.AppendLine($"{indent}ShowLabel = true,");
                sb.AppendLine($"{indent}Height = {FormatNum(GetNumProp(node, "Height", 12))}");
                sb.AppendLine("})");
                break;

            case WidgetType.Badge:
                var badgeCol = GetProp(node, "Color", "#00C864");
                var bc = ThemeModel.HexToColor(badgeCol);
                var badgeTc = GetProp(node, "TextColor", "#000000");
                var btc = ThemeModel.HexToColor(badgeTc);
                EmitWidgetStart(sb, tabVar, node, "CreateBadge", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Badge"))}\",");
                sb.AppendLine($"{indent}Text = \"{EscapeLua(GetProp(node, "Text", "Badge"))}\",");
                sb.AppendLine($"{indent}Color = Color3.fromRGB({bc.R}, {bc.G}, {bc.B}),");
                sb.AppendLine($"{indent}TextColor = Color3.fromRGB({btc.R}, {btc.G}, {btc.B})");
                sb.AppendLine("})");
                break;

            case WidgetType.Table:
                EmitWidgetStart(sb, tabVar, node, "CreateTable", minify);
                sb.AppendLine($"{indent}Name = \"{EscapeLua(GetProp(node, "Name", "Table"))}\",");
                var cols = node.Props["Columns"];
                var colList = cols is ObservableCollection<string> cl ? cl.ToList() : new List<string>();
                sb.Append($"{indent}Columns = {{");
                sb.Append(string.Join(", ", colList.Select(c => $"\"{EscapeLua(c)}\"")));
                sb.AppendLine("},");
                sb.AppendLine($"{indent}Rows = {{}},");
                sb.AppendLine($"{indent}RowHeight = {FormatNum(GetNumProp(node, "RowHeight", 28))},");
                sb.AppendLine($"{indent}MaxHeight = {FormatNum(GetNumProp(node, "MaxHeight", 200))}");
                sb.AppendLine("})");
                break;
        }
    }

    private void EmitWidgetStart(StringBuilder sb, string tabVar, UINode node, string constructor, bool minify)
    {
        if (node.BindVariable != null)
            sb.Append($"local {node.BindVariable} = ");
        sb.AppendLine($"{tabVar}:{constructor}({{");
    }

    private void EmitWithOptionalBinding(StringBuilder sb, string tabVar, UINode node, bool minify, string? inlineCall)
    {
        if (inlineCall != null)
        {
            if (node.BindVariable != null)
                sb.AppendLine($"local {node.BindVariable} = {inlineCall}");
            else
                sb.AppendLine(inlineCall);
        }
    }

    private void EmitWidgetWithConfig(StringBuilder sb, string tabVar, UINode node, string constructor, bool minify,
        (string key, string value, string type)[] props)
    {
        var indent = minify ? "" : "    ";
        EmitWidgetStart(sb, tabVar, node, constructor, minify);

        foreach (var (key, value, type) in props)
        {
            if (type == "string")
                sb.AppendLine($"{indent}{key} = \"{EscapeLua(value)}\",");
            else if (type == "literal")
                sb.AppendLine($"{indent}{key} = {value},");
            else if (type == "callback")
            {
                sb.AppendLine($"{indent}Callback = function(value)");
                EmitCallbackBody(sb, node, indent + indent);
                sb.AppendLine($"{indent}end");
            }
        }

        sb.AppendLine("})");
    }

    private void EmitCallbackBody(StringBuilder sb, UINode node, string indent)
    {
        if (!string.IsNullOrWhiteSpace(node.CallbackCode))
        {
            foreach (var line in node.CallbackCode.Split('\n'))
                sb.AppendLine($"{indent}{line.TrimEnd()}");
        }
        else
        {
            sb.AppendLine($"{indent}--[[ TODO: Add your callback here ]]");
        }
    }

    private string MakeSafeVarName(string prefix, string name)
    {
        var safe = Regex.Replace(name, @"[^a-zA-Z0-9_]", "");
        if (string.IsNullOrEmpty(safe)) safe = "Unnamed";
        if (char.IsDigit(safe[0])) safe = "_" + safe;

        var candidate = $"{prefix}_{safe}";
        var final = candidate;
        var counter = 2;
        while (_usedVarNames.Contains(final))
        {
            final = $"{candidate}_{counter}";
            counter++;
        }
        _usedVarNames.Add(final);
        return final;
    }

    private static string EscapeLua(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");

    private static string GetProp(UINode node, string key, string defaultVal) =>
        node.Props[key]?.ToString() ?? defaultVal;

    private static double GetNumProp(UINode node, string key, double defaultVal) =>
        node.Props[key] is double d ? d : defaultVal;

    private static bool GetBoolProp(UINode node, string key) =>
        node.Props[key] is true;

    private static string FormatNum(double v) =>
        v == Math.Floor(v) ? ((int)v).ToString() : v.ToString("G");

    private static bool ProjectUsesUpgradedFeatures(StarLibProject project) =>
        project.Tabs.Any(t => t.Nodes.Any(n =>
            n.Type is WidgetType.Separator or WidgetType.Spacer or WidgetType.ProgressBar
            or WidgetType.Badge or WidgetType.Table or WidgetType.HorizontalRow
            or WidgetType.VerticalStack or WidgetType.GridContainer));

    private static string Minify(string lua)
    {
        var lines = lua.Split('\n')
            .Select(l => l.Trim())
            .Where(l => !l.StartsWith("--"))
            .Where(l => !string.IsNullOrWhiteSpace(l));
        return string.Join(" ", lines);
    }
}
