using System.Collections.ObjectModel;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using StarLibEditor.Models;

namespace StarLibEditor.Services;

public class CodeGeneratorService
{
    private readonly HashSet<string> _usedVarNames = new();

    public string Generate(StarLibProject project, bool minify = false)
    {
        _usedVarNames.Clear();
        var sb = new StringBuilder();

        if (!minify)
        {
            sb.AppendLine($"-- Generated by StarLib Editor v{project.Meta.AppVersion}");
            sb.AppendLine($"-- Project: {project.Meta.ProjectName}");
            sb.AppendLine($"-- Exported: {DateTime.UtcNow:o}");
            sb.AppendLine();
        }

        sb.AppendLine($"local StarLib = loadstring(readfile(\"{EscapeLua(project.Settings.StarLibPath.Replace("\\", "/"))}\"))()");
        sb.AppendLine();

        GenerateWindowConfig(sb, project, minify);
        sb.AppendLine();

        foreach (var tab in project.Tabs)
        {
            GenerateTab(sb, tab, minify);
            sb.AppendLine();
        }

        var result = sb.ToString();
        return minify ? Minify(result) : result;
    }

    private void GenerateWindowConfig(StringBuilder sb, StarLibProject project, bool minify)
    {
        var w = project.Window;
        var indent = minify ? "" : "    ";
        var nl = minify ? " " : "\n";

        if (!minify) sb.AppendLine("-- Window");
        sb.Append("local Window = StarLib:CreateWindow({");

        sb.Append($"{nl}{indent}Name = \"{EscapeLua(w.Name)}\",");
        sb.Append($"{nl}{indent}LoadingTitle = \"{EscapeLua(w.LoadingTitle)}\",");
        sb.Append($"{nl}{indent}LoadingSubtitle = \"{EscapeLua(w.LoadingSubtitle)}\",");
        sb.Append($"{nl}{indent}Theme = \"{EscapeLua(w.ThemePreset)}\",");
        sb.Append($"{nl}{indent}Resizable = {ToLuaBool(w.Resizable)},");
        sb.Append($"{nl}{indent}EnableSearch = {ToLuaBool(w.EnableSearch)},");
        if (!string.IsNullOrWhiteSpace(w.Icon))
            sb.Append($"{nl}{indent}Icon = \"{EscapeLua(w.Icon)}\",");
        if (!string.IsNullOrWhiteSpace(w.ToggleKey))
            sb.Append($"{nl}{indent}ToggleKey = Enum.KeyCode.{w.ToggleKey},");

        sb.Append($"{nl}{indent}ConfigurationSaving = {{");
        sb.Append($"{nl}{indent}{indent}Enabled = {ToLuaBool(w.ConfigurationSaving.Enabled)},");
        sb.Append($"{nl}{indent}{indent}FolderName = \"{EscapeLua(w.ConfigurationSaving.FolderName)}\",");
        sb.Append($"{nl}{indent}{indent}FileName = \"{EscapeLua(w.ConfigurationSaving.FileName)}\"");
        sb.Append($"{nl}{indent}}},");

        sb.Append($"{nl}{indent}Discord = {{");
        sb.Append($"{nl}{indent}{indent}Enabled = {ToLuaBool(w.Discord.Enabled)},");
        sb.Append($"{nl}{indent}{indent}Invite = \"{EscapeLua(w.Discord.Invite)}\",");
        sb.Append($"{nl}{indent}{indent}RememberJoins = {ToLuaBool(w.Discord.RememberPrompt)}");
        sb.Append($"{nl}{indent}}},");

        var keys = ParseCsv(w.KeySystem.ValidKeysCsv);
        sb.Append($"{nl}{indent}KeySystem = {{");
        sb.Append($"{nl}{indent}{indent}Enabled = {ToLuaBool(w.KeySystem.Enabled)},");
        sb.Append($"{nl}{indent}{indent}Title = \"{EscapeLua(w.KeySystem.Title)}\",");
        sb.Append($"{nl}{indent}{indent}Subtitle = \"{EscapeLua(w.KeySystem.Subtitle)}\",");
        sb.Append($"{nl}{indent}{indent}Note = \"{EscapeLua(w.KeySystem.Note)}\",");
        sb.Append($"{nl}{indent}{indent}SaveKey = \"{EscapeLua(w.KeySystem.SaveKey)}\",");
        sb.Append($"{nl}{indent}{indent}GrabKeyFromSite = {ToLuaBool(w.KeySystem.GrabKeyFromSite)},");
        sb.Append($"{nl}{indent}{indent}KeyUrl = \"{EscapeLua(w.KeySystem.KeyUrl)}\",");
        sb.Append($"{nl}{indent}{indent}Keys = {{ {string.Join(", ", keys.Select(k => $"\"{EscapeLua(k)}\""))} }}");
        sb.Append($"{nl}{indent}}},");

        sb.Append($"{nl}{indent}Monetization = {{");
        sb.Append($"{nl}{indent}{indent}Enabled = {ToLuaBool(w.Monetization.Enabled)},");
        sb.Append($"{nl}{indent}{indent}Strategy = \"{EscapeLua(w.Monetization.Strategy)}\",");
        sb.Append($"{nl}{indent}{indent}Details = \"{EscapeLua(w.Monetization.Details)}\"");
        sb.Append($"{nl}{indent}}}");

        var themeOverrides = w.Theme.GetOverrides();
        if (themeOverrides.Count > 0)
        {
            sb.Append($",{nl}{indent}ThemeOverrides = {{");
            var first = true;
            foreach (var kv in themeOverrides.OrderBy(k => k.Key))
            {
                if (!first) sb.Append(",");
                first = false;
                var rgb = ThemeModel.HexToColor(kv.Value);
                sb.Append($"{nl}{indent}{indent}{kv.Key} = Color3.fromRGB({rgb.R}, {rgb.G}, {rgb.B})");
            }
            sb.Append($"{nl}{indent}}}");
        }

        sb.AppendLine($"{nl}}})");
    }

    private void GenerateTab(StringBuilder sb, TabModel tab, bool minify)
    {
        var tabVar = MakeSafeVarName("Tab", tab.Name);

        if (!minify) sb.AppendLine($"-- Tab: {tab.Name}");
        sb.AppendLine($"local {tabVar} = Window:CreateTab({{");
        sb.AppendLine($"    Name = \"{EscapeLua(tab.Name)}\",");
        if (!string.IsNullOrWhiteSpace(tab.Icon))
            sb.AppendLine($"    Icon = \"{EscapeLua(tab.Icon)}\"");
        else
            sb.AppendLine("    Icon = \"square\"");
        sb.AppendLine("})");

        foreach (var node in tab.Nodes)
        {
            if (!node.Enabled) continue;
            GenerateNode(sb, tabVar, node);
        }
    }

    private void GenerateNode(StringBuilder sb, string tabVar, UINode node)
    {
        switch (node.Type)
        {
            case WidgetType.Section:
                sb.AppendLine($"{tabVar}:CreateSection(\"{EscapeLua(GetProp(node, "Text", "Section"))}\")");
                return;
            case WidgetType.Label:
                EmitInlineOrBound(sb, node, $"{tabVar}:CreateLabel(\"{EscapeLua(GetProp(node, "Text", "Label"))}\")");
                return;
            case WidgetType.Paragraph:
                EmitInlineOrBound(sb, node,
                    $"{tabVar}:CreateParagraph({{Title = \"{EscapeLua(GetProp(node, "Title", ""))}\", Content = \"{EscapeLua(GetProp(node, "Content", ""))}\"}})");
                return;
            case WidgetType.Button:
                EmitWidgetStart(sb, node, tabVar, "CreateButton");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Button"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine("    Callback = function()");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Toggle:
                EmitWidgetStart(sb, node, tabVar, "CreateToggle");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Toggle"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine($"    CurrentValue = {ToLuaBool(GetBoolProp(node, "CurrentValue"))},");
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "ToggleFlag"))}\",");
                sb.AppendLine("    Callback = function(value)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Slider:
                EmitWidgetStart(sb, node, tabVar, "CreateSlider");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Slider"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine($"    Range = {{{FormatNum(GetNumProp(node, "Min", 0))}, {FormatNum(GetNumProp(node, "Max", 100))}}},");
                sb.AppendLine($"    Increment = {FormatNum(GetNumProp(node, "Increment", 1))},");
                sb.AppendLine($"    Suffix = \"{EscapeLua(GetProp(node, "Suffix", ""))}\",");
                sb.AppendLine($"    CurrentValue = {FormatNum(GetNumProp(node, "CurrentValue", 50))},");
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "SliderFlag"))}\",");
                sb.AppendLine("    Callback = function(value)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Dropdown:
                var options = GetStringCollection(node, "Options");
                var multi = GetBoolProp(node, "MultipleOptions");
                EmitWidgetStart(sb, node, tabVar, "CreateDropdown");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Dropdown"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine($"    Options = {{ {string.Join(", ", options.Select(o => $"\"{EscapeLua(o)}\""))} }},");
                sb.AppendLine($"    MultipleOptions = {ToLuaBool(multi)},");
                if (multi)
                {
                    var selected = ParseCsv(GetProp(node, "CurrentOption", ""));
                    if (selected.Count == 0 && options.Count > 0) selected.Add(options[0]);
                    sb.AppendLine($"    CurrentOption = {{ {string.Join(", ", selected.Select(o => $"\"{EscapeLua(o)}\""))} }},");
                }
                else
                {
                    sb.AppendLine($"    CurrentOption = \"{EscapeLua(GetProp(node, "CurrentOption", options.FirstOrDefault() ?? ""))}\",");
                }
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "DropdownFlag"))}\",");
                sb.AppendLine("    Callback = function(value)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Input:
                EmitWidgetStart(sb, node, tabVar, "CreateInput");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Input"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine($"    PlaceholderText = \"{EscapeLua(GetProp(node, "PlaceholderText", "..."))}\",");
                sb.AppendLine($"    RemoveTextAfterFocusLost = {ToLuaBool(GetBoolProp(node, "RemoveTextAfterFocusLost"))},");
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "InputFlag"))}\",");
                sb.AppendLine("    Callback = function(text)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Keybind:
                EmitWidgetStart(sb, node, tabVar, "CreateKeybind");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Keybind"))}\",");
                sb.AppendLine($"    CurrentKeybind = \"{EscapeLua(GetProp(node, "Default", "F"))}\",");
                sb.AppendLine($"    HoldToInteract = {ToLuaBool(GetBoolProp(node, "HoldToInteract"))},");
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "KeybindFlag"))}\",");
                sb.AppendLine("    Callback = function(key)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.ColorPicker:
                var color = ThemeModel.HexToColor(GetProp(node, "Default", "#FFFFFF"));
                EmitWidgetStart(sb, node, tabVar, "CreateColorPicker");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Color"))}\",");
                EmitCommonWidgetProps(sb, node);
                sb.AppendLine($"    Color = Color3.fromRGB({color.R}, {color.G}, {color.B}),");
                sb.AppendLine($"    Flag = \"{EscapeLua(GetProp(node, "Flag", "ColorFlag"))}\",");
                sb.AppendLine("    Callback = function(value)");
                EmitCallbackBody(sb, node, "        ");
                sb.AppendLine("    end");
                sb.AppendLine("})");
                return;
            case WidgetType.Stat:
                EmitWidgetStart(sb, node, tabVar, "CreateStat");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Stat"))}\",");
                sb.AppendLine($"    Value = \"{EscapeLua(GetProp(node, "Value", "0"))}\",");
                sb.AppendLine($"    Suffix = \"{EscapeLua(GetProp(node, "Suffix", ""))}\"");
                sb.AppendLine("})");
                return;
            case WidgetType.Separator:
                sb.AppendLine($"{tabVar}:CreateSeparator()");
                return;
            case WidgetType.Spacer:
                sb.AppendLine($"{tabVar}:CreateSpacer({{ Height = {FormatNum(GetNumProp(node, "Height", 10))} }})");
                return;
            case WidgetType.ProgressBar:
                EmitWidgetStart(sb, node, tabVar, "CreateProgressBar");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Progress"))}\",");
                sb.AppendLine($"    Min = {FormatNum(GetNumProp(node, "Min", 0))},");
                sb.AppendLine($"    Max = {FormatNum(GetNumProp(node, "Max", 100))},");
                sb.AppendLine($"    Default = {FormatNum(GetNumProp(node, "Default", 0))},");
                sb.AppendLine($"    ShowLabel = {ToLuaBool(GetBoolProp(node, "ShowLabel"))},");
                sb.AppendLine($"    Height = {FormatNum(GetNumProp(node, "Height", 12))}");
                sb.AppendLine("})");
                return;
            case WidgetType.Badge:
                var bc = ThemeModel.HexToColor(GetProp(node, "Color", "#00C864"));
                var btc = ThemeModel.HexToColor(GetProp(node, "TextColor", "#000000"));
                EmitWidgetStart(sb, node, tabVar, "CreateBadge");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Badge"))}\",");
                sb.AppendLine($"    Text = \"{EscapeLua(GetProp(node, "Text", "Badge"))}\",");
                sb.AppendLine($"    Color = Color3.fromRGB({bc.R}, {bc.G}, {bc.B}),");
                sb.AppendLine($"    TextColor = Color3.fromRGB({btc.R}, {btc.G}, {btc.B})");
                sb.AppendLine("})");
                return;
            case WidgetType.Table:
                var cols = GetStringCollection(node, "Columns");
                EmitWidgetStart(sb, node, tabVar, "CreateTable");
                sb.AppendLine($"    Name = \"{EscapeLua(GetProp(node, "Name", "Table"))}\",");
                sb.AppendLine($"    Columns = {{ {string.Join(", ", cols.Select(c => $"\"{EscapeLua(c)}\""))} }},");
                sb.AppendLine("    Rows = {},");
                sb.AppendLine($"    RowHeight = {FormatNum(GetNumProp(node, "RowHeight", 28))},");
                sb.AppendLine($"    MaxHeight = {FormatNum(GetNumProp(node, "MaxHeight", 200))}");
                sb.AppendLine("})");
                return;
            default:
                sb.AppendLine($"-- Unsupported widget in exporter: {node.Type}");
                return;
        }
    }

    private static void EmitCommonWidgetProps(StringBuilder sb, UINode node)
    {
        var desc = GetProp(node, "Description", "");
        var icon = GetProp(node, "Icon", "");
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine($"    Description = \"{EscapeLua(desc)}\",");
        if (!string.IsNullOrWhiteSpace(icon))
            sb.AppendLine($"    Icon = \"{EscapeLua(icon)}\",");
    }

    private static void EmitWidgetStart(StringBuilder sb, UINode node, string tabVar, string constructor)
    {
        if (!string.IsNullOrWhiteSpace(node.BindVariable))
            sb.Append($"local {node.BindVariable} = ");
        sb.AppendLine($"{tabVar}:{constructor}({{");
    }

    private static void EmitInlineOrBound(StringBuilder sb, UINode node, string inlineCall)
    {
        if (!string.IsNullOrWhiteSpace(node.BindVariable))
            sb.AppendLine($"local {node.BindVariable} = {inlineCall}");
        else
            sb.AppendLine(inlineCall);
    }

    private static void EmitCallbackBody(StringBuilder sb, UINode node, string indent)
    {
        if (!string.IsNullOrWhiteSpace(node.CallbackCode))
        {
            foreach (var line in node.CallbackCode.Split('\n'))
                sb.AppendLine($"{indent}{line.TrimEnd()}");
            return;
        }

        sb.AppendLine($"{indent}--[[ TODO: Add your callback here ]]");
    }

    private string MakeSafeVarName(string prefix, string name)
    {
        var safe = Regex.Replace(name, @"[^a-zA-Z0-9_]", "");
        if (string.IsNullOrEmpty(safe)) safe = "Unnamed";
        if (char.IsDigit(safe[0])) safe = "_" + safe;

        var candidate = $"{prefix}_{safe}";
        var final = candidate;
        var counter = 2;
        while (_usedVarNames.Contains(final))
        {
            final = $"{candidate}_{counter}";
            counter++;
        }
        _usedVarNames.Add(final);
        return final;
    }

    private static string EscapeLua(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");

    private static string GetProp(UINode node, string key, string defaultVal) =>
        node.Props[key]?.ToString() ?? defaultVal;

    private static double GetNumProp(UINode node, string key, double defaultVal)
    {
        var value = node.Props[key];
        return value switch
        {
            double d => d,
            int i => i,
            string s when double.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var parsed) => parsed,
            _ => defaultVal
        };
    }

    private static bool GetBoolProp(UINode node, string key) =>
        node.Props[key] is true;

    private static List<string> GetStringCollection(UINode node, string key)
    {
        if (node.Props[key] is ObservableCollection<string> oc)
            return oc.ToList();
        if (node.Props[key] is IEnumerable<string> ie)
            return ie.ToList();
        if (node.Props[key] is string s && !string.IsNullOrWhiteSpace(s))
            return ParseCsv(s);
        return new List<string>();
    }

    private static List<string> ParseCsv(string csv) =>
        csv.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(x => x.Trim())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .ToList();

    private static string ToLuaBool(bool value) => value ? "true" : "false";

    private static string FormatNum(double v) =>
        v == Math.Floor(v) ? ((int)v).ToString(CultureInfo.InvariantCulture) : v.ToString("G", CultureInfo.InvariantCulture);

    private static string Minify(string lua)
    {
        var lines = lua.Split('\n')
            .Select(l => l.Trim())
            .Where(l => !l.StartsWith("--"))
            .Where(l => !string.IsNullOrWhiteSpace(l));
        return string.Join(" ", lines);
    }
}
