-- Generated by StarLib Editor v1.0.0
-- Project: Sample Script
-- This is an example of output from the code generator

local StarLib = loadstring(readfile("StarLib/StarLib.lua"))()

-- Window
local Window = StarLib:CreateWindow({
    Name = "Sample Script",
    ToggleKey = Enum.KeyCode.RightShift
})

-- Tab: Main
local Tab_Main = Window:CreateTab("Main")
Tab_Main:CreateSection("General")
Tab_Main:CreateButton({
    Name = "Print Hello",
    Callback = function()
        print("Hello from StarLib!")
    end
})
local Tgl_Fly = Tab_Main:CreateToggle({
    Name = "Fly",
    CurrentValue = false,
    Callback = function(value)
        print("Fly:", value)
    end
})
local Sld_Speed = Tab_Main:CreateSlider({
    Name = "Speed",
    Range = {0, 100},
    CurrentValue = 16,
    Increment = 1,
    Callback = function(value)
        print("Speed:", value)
    end
})

-- Tab: Settings
local Tab_Settings = Window:CreateTab("Settings")
Tab_Settings:CreateSection("Visual")
Tab_Settings:CreateDropdown({
    Name = "Theme",
    Options = {"Dark", "Light", "Blue"},
    Default = "Dark",
    Callback = function(value)
        print("Theme:", value)
    end
})
Tab_Settings:CreateInput({
    Name = "Username",
    PlaceholderText = "Enter name...",
    Default = "",
    Callback = function(text)
        print("Username:", text)
    end
})
Tab_Settings:CreateKeybind({
    Name = "Toggle GUI",
    Default = Enum.KeyCode.RightShift,
    Callback = function(key)
        print("Keybind set to:", key.Name)
    end
})
Tab_Settings:CreateColorPicker({
    Name = "Accent Color",
    Default = Color3.fromRGB(0, 170, 255),
    Callback = function(color)
        print("Color:", color)
    end
})

-- Notification
Window:Notify({
    Title = "Welcome!",
    Content = "Sample script loaded successfully.",
    Duration = 4
})
